/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as VeiculoIdRouteImport } from './routes/veiculo.$id'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as AuthenticatedEstoqueIdRouteImport } from './routes/_authenticated/estoque.$id'
import { Route as AuthenticatedEstoqueNovoRouteImport } from './routes/_authenticated/estoque.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VeiculoIdRoute = VeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIdRoute = AuthenticatedEstoqueIdRouteImport.update({
  id: '/estoque/$id',
  path: '/estoque/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueNovoRoute =
  AuthenticatedEstoqueNovoRouteImport.update({
    id: '/estoque/novo',
    path: '/estoque/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculo/$id': typeof VeiculoIdRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculo/$id': typeof VeiculoIdRoute
  '/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculo/$id': typeof VeiculoIdRoute
  '/_authenticated/estoque/$id': typeof AuthenticatedEstoqueIdRoute
  '/_authenticated/estoque/novo': typeof AuthenticatedEstoqueNovoRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/financeiro'
    | '/leads'
    | '/painel'
    | '/pessoas'
    | '/relatorios'
    | '/veiculo/$id'
    | '/estoque/$id'
    | '/estoque/novo'
    | '/estoque/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/financeiro'
    | '/leads'
    | '/painel'
    | '/pessoas'
    | '/relatorios'
    | '/veiculo/$id'
    | '/estoque/$id'
    | '/estoque/novo'
    | '/estoque'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/financeiro'
    | '/_authenticated/leads'
    | '/_authenticated/painel'
    | '/_authenticated/pessoas'
    | '/_authenticated/relatorios'
    | '/veiculo/$id'
    | '/_authenticated/estoque/$id'
    | '/_authenticated/estoque/novo'
    | '/_authenticated/estoque/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VeiculoIdRoute: typeof VeiculoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/veiculo/$id': {
      id: '/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/veiculo/$id'
      preLoaderRoute: typeof VeiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/$id': {
      id: '/_authenticated/estoque/$id'
      path: '/estoque/$id'
      fullPath: '/estoque/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/novo': {
      id: '/_authenticated/estoque/novo'
      path: '/estoque/novo'
      fullPath: '/estoque/novo'
      preLoaderRoute: typeof AuthenticatedEstoqueNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedEstoqueIdRoute: typeof AuthenticatedEstoqueIdRoute
  AuthenticatedEstoqueNovoRoute: typeof AuthenticatedEstoqueNovoRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedEstoqueIdRoute: AuthenticatedEstoqueIdRoute,
  AuthenticatedEstoqueNovoRoute: AuthenticatedEstoqueNovoRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VeiculoIdRoute: VeiculoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
